version: '3'

services:
  mjpeg-relay:
    container_name: WS-Stream-Viewer
    build: .
    ports:
      - "10000:10000"
    environment:
      - SOURCE_WEBSOCKET=ws://10.242.176.200:8888/ws
      - HOST_IP=172.27.65.25
      - PORT=10000
      - RECONNECT_INTERVAL=5000
      - MAX_FPS=30
    restart: unless-stopped
